services:
  artist-api:
    image: gitlab-depinfo.univ-brest.fr:5050/e22200893/apis/artist-api:v1.0.4
    ports:
      - "10063:8083"
    environment:
      DB_HOST: artistdb
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: monMotDePasseSuperSecret
    depends_on:
      - artistdb



  artistdb:
    image: mariadb:11.6.2-ubi9
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
    volumes:
      - ./data_artist:/var/lib/mysql